-- MySQL Script generated by MySQL Workbench
-- Sun Nov 13 17:57:01 2022
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS,
FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE,
SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_I
N_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SU
BSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Size`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Size` (
`size id` INT NOT NULL,
`size code` VARCHAR(45) NULL,
`sort order` VARCHAR(45) NULL,
PRIMARY KEY (`size id`));

-- -----------------------------------------------------
-- Table `mydb`.`Color`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Color` (
`Color id` INT NOT NULL,
`color code` VARCHAR(45) NULL,
`color name` VARCHAR(45) NULL,
PRIMARY KEY (`Color id`));

-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
`product name` INT NOT NULL,
`product id` VARCHAR(45) NULL,
`color id` VARCHAR(45) NULL,
`size id` VARCHAR(45) NULL,
PRIMARY KEY (`product name`),
CONSTRAINT `fk_Product_1`
FOREIGN KEY (`product name`)
REFERENCES `mydb`.`Size` (`size id`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT `fk_Product_2`
FOREIGN KEY (`product name`)
REFERENCES `mydb`.`Color` (`Color id`)
ON DELETE NO ACTION
ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
`category_id` INT NOT NULL,
`name` VARCHAR(255) NOT NULL,
PRIMARY KEY (`category_id`),
CONSTRAINT `fk_category_1`
FOREIGN KEY ()
REFERENCES `mydb`.`Product` ()
ON DELETE NO ACTION
ON UPDATE NO ACTION);
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;